version: '3'

services:
  oracledb:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracledb
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=oraclepass
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./data:/opt/oracle/oradata
    restart: always
