-- Resposta do Comando SQL item a)

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'COMERCIAL', 'A');

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'CONTABILIDADE','A');

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'ESTOQUE', 'A');

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'FINANCEIRO', 'A');

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'SERVICO_DE_ATENDIMENTO_AO_CLIENTE', 'A');

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'RECURSOS_HUMANOS', 'A');

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'LOGISTICA', 'A');

SELECT * FROM MC_DEPTO;

-- Resposta do Comando SQL item b)

select * from MC_FUNCIONARIO;

-- registro de funcionários no depto 3 Comercial

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, 1, 'Valeria Messa', 'Gerente Comercial', 8750, TO_DATE('15072021','DDMMYYYY'), TO_DATE('11061990','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Lee Parker', 'Vendedor', 3600, TO_DATE('01081990','DDMMYYYY'), TO_DATE('12121981','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Pedro Silva', 'Vendedor', 3600, TO_DATE('14022019','DDMMYYYY'), TO_DATE('01021999','DDMMYYYY'));


-- registro de funcionários no depto 4 Contabilidade

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, 1, 'Martha Salas', 'Gerente Contábil', 8750, TO_DATE('14022020','DDMMYYYY'), TO_DATE('10022001','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Antonio Paredes', 'Analista Contábil senior', 6500, TO_DATE('01012000','DDMMYYYY'), TO_DATE('04051985','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Carla Penha', 'Analista Contábil Jr.', 4500, TO_DATE('01012000','DDMMYYYY'), TO_DATE('24061991','DDMMYYYY'));


-- registro de funcionários no depto 5 Estoque

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, 1, 'Bruno Santos', 'Gerente de Estoque', 8500, TO_DATE('01011990','DDMMYYYY'), TO_DATE('01011970','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Ana Paula Oliveira', 'Analista de Estoque', 3000, TO_DATE('14022020','DDMMYYYY'), TO_DATE('10022001','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Carla Silva', 'Assistente de Estoque', 2000, TO_DATE('0302198','DDMMYYYY'), TO_DATE('19011985','DDMMYYYY'));


-- registro de funcionários no depto 6 Financeiro

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, 1, 'Fernanda Oliveira', 'Gerente Financeiro', 7850, TO_DATE('23052006','DDMMYYYY'), TO_DATE('12031989','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Diego Alves', 'Analista Financeiro', 4500, TO_DATE('13072007','DDMMYYYY'), TO_DATE('24061988','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Guilherme Santos', 'Assistente Financeiro', 2800, TO_DATE('01012000','DDMMYYYY'), TO_DATE('18042001','DDMMYYYY'));


-- registro de funcionários no depto 7 SAC

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, 1, 'Luana Souza', 'Gerente de SAC', 7500, TO_DATE('11022023','DDMMYYYY'), TO_DATE('31031998','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, SQ_MC_FUNCIONARIO.CURRVAL-1, 'João Silva', ' Analista de SAC', 4800, TO_DATE('13122017','DDMMYYYY'), TO_DATE('01011992','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Marcelo Almeida', 'Assistente de SAC', 5500, TO_DATE('25061999','DDMMYYYY'), TO_DATE('12121987','DDMMYYYY'));


-- registro de funcionários no depto 8 RHH

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, 1, 'Pedro Rocha', 'Gerente de RH', 7500, TO_DATE('01012000','DDMMYYYY'), TO_DATE('04051985','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Nathalia Costa', 'Analista de RH', 5500, TO_DATE('14022020','DDMMYYYY'), TO_DATE('19081998','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Raquel Santos', 'Assistente de RH', 4500, TO_DATE('06062016','DDMMYYYY'), TO_DATE('05051985','DDMMYYYY'));


-- registro de funcionários no depto 9 Logistica

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, 1, 'Vanessa Rodrigues', 'Gerente de Logística', 7500, TO_DATE('01012021','DDMMYYYY'), TO_DATE('04081998','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, SQ_MC_FUNCIONARIO.CURRVAL-1, 'Thiago Martins', 'Analista de Logística', 4500, TO_DATE('13051993','DDMMYYYY'), TO_DATE('10022001','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, SQ_MC_FUNCIONARIO.CURRVAL-2, 'Wagner Almeida', 'Assistente de Logística', 5500, TO_DATE('01012022','DDMMYYYY'), TO_DATE('13051999','DDMMYYYY'));


-- Resposta do Comando SQL item c)

INSERT ALL
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AC', 'Acre')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AL', 'Alagoas')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AP', 'Amapá')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AM', 'Amazonas')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('BA', 'Bahia')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('CE', 'Ceará')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('DF', 'Distrito Federal')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('ES', 'Espírito Santo')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('GO', 'Goiás')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MA', 'Maranhão')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MT', 'Mato Grosso')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MS', 'Mato Grosso do Sul')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MG', 'Minas Gerais')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PA', 'Pará')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PB', 'Paraíba')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PR', 'Paraná')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PE', 'Pernambuco')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PI', 'Piauí')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RJ', 'Rio de Janeiro')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RN', 'Rio Grande do Norte')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RS', 'Rio Grande do Sul')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RO', 'Rondônia')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RR', 'Roraima')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SC', 'Santa Catarina')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SP', 'São Paulo')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SE', 'Sergipe')
   INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('TO', 'Tocantins')
SELECT 1 FROM DUAL;

SELECT * FROM MC_ESTADO;


-- Resposta do Comando SQL item c)

-- Registro de cidades

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'BA', 'Feira de Santana', 2910800, 075);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'BA', 'Salvador', 2927408, 071);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'Belo Horizonte', 3106200, 031);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'Uberlândia', 3170107, 034);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'RJ', 'Niterói', 3303302, 021);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'RJ', 'Rio de Janeiro', 3304557, 021);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'Blumenau', 4202404, 047);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'Florianópolis', 4205407, 048);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'Campinas', 3509502, 019);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'São Paulo', 3550308, 011);

SELECT * FROM MC_CIDADE;

-- Registro de bairros


INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '1', 'Centro', 'Zona Centro');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '1', 'Queimadinha', 'Zona Leste');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '2', 'Barra', 'Zona Orla');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '2', 'Rio Vermelho', 'Zona Cidade Baixa');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '3', 'Funcionários', 'Zona Centro-Sul ');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '3', 'Savassi', 'Zona Centro-Sul ');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '4', 'Centro', 'Zona Centro');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '4', 'Jardim Patrícia', 'Zona Leste');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '5', 'Icaraí', 'Zona Zona Sul');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '5', 'São Francisco', 'Zona Zona Sul');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '6', 'Botafogo', 'Zona Zona Sul');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '6', 'Copacabana', 'Zona Zona Sul');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '7', 'Centro', 'Zona Centro');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '7', 'Itoupava Seca', 'Zona Norte');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '8', 'Centro', 'Zona Norte');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '8', 'Trindade', 'Zona Leste');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '9', 'Barão Geraldo', 'Zona Centro');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '9', 'Cambuí', 'Zona Oeste');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '10', 'Moema', 'Zona Sul');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, '10', 'Vila Madalena', 'Zona Oeste');

SELECT * FROM MC_BAIRRO;

-- Registro de logradouros

INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '1', 'Rua de Santana', 44002104);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '1', 'Avenida Getúlio Vargas - de 581 a 1163', 44001325);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '2', 'Caminho da Rondônia', 44050488);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '2', 'Avenida José Falcão da Silva', 44050512);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '3', 'Rua Barão de Itapoan', 40140060);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '3', 'Avenida Oceânica', 40140130);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '4', 'Rua João Gomes', 41950640);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '4', 'Rua Fonte do Boi', 41940360);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '5', 'Avenida Afonso Pena - de 2661 a 3279', 30130011);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '5', 'Avenida Getúlio Vargas - até 549/550', 30112020);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '6', 'Rua Tomé de Souza - até 359/360', 30140130);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '6', 'Rua Paraíba - de 1231/1232 ao fim', 30130148);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '7', 'Avenida João Pinheiro - até 618/0619', 38400124);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '7', 'Avenida Afonso Pena - até 568/569', 38400128);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '8', 'Rua Piroxênio', 38414130);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '8', 'Avenida do Óleo', 38414224);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '9', 'Av Jornalista Alberto Francisco Torres', 24230001);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '9', 'Rua Mariz e Barros - lado ímpar', 24220120);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '10', 'Avenida Quintino Bocaiúva - até 365', 24360022);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '10', 'Rua Doutor Henrique Portugal', 24360080);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '11', 'Praia Botafogo - até 284 - lado par', 22250040);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '11', 'Rua Voluntários da Pátria - até 154', 22270010);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '12', 'Rua Siqueira Campos - de 1 ao fim', 22031071);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '12', 'Avenida Nossa Senhora de Copacabana', 22020001);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '13', 'Rua Horácio Antônio Braun', 89010006);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '13', 'Rua 15 de Novembro - até 913 - lado ímpar', 89010001);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '14', 'Rua Francisco Vahldieck - até 653/654', 89053188);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '14', 'Rua Iguaçu', 89030030);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '15', 'Rua Deodoro', 88010020);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '15', 'Rua Felipe Schmidt - até 348/349', 88010000);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '16', 'Rua Lauro Linhares', 88036000);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '16', 'Rua Laércio Costa', 88036310);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '17', 'Avenida Santa Isabel', 13083852);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '17', 'Estrada Municipal Weimar Morandi', 13085850);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '18', 'Rua Coronel Quirino', 13025004);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '18', 'Rua Conceição', 13025355);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '19', 'Avenida Moema - até 349/350', 04077020);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '19', 'Avenida Ibirapuera', 14784128);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '20', 'Rua dos Tamanás', 05444010);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, '20', 'Rua Harmonia', 05435001);

SELECT * FROM MC_LOGRADOURO;

-- Resposta do Comando SQL item d)

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('1', '26', '106', 'Apartamento', TO_DATE('30102000','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('2', '12', '47', 'Casa', TO_DATE('01072005','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('3', '37', '13', 'Vila', TO_DATE('10062020','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('4', '8', '68', 'Apartamento', TO_DATE('27022021','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('5', '24', '82', 'Condominio', TO_DATE('08082008','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('6', '1', '89', 'Apartamento', TO_DATE('07062004','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('7', '23', '7', 'Casa', TO_DATE('01072008','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('8', '13', '75', 'Vila', TO_DATE('22112017','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('9', '11', '132', 'Apartamento', TO_DATE('10092002','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('10', '37', '74', 'Condominio', TO_DATE('20072012','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('11', '17', '41', 'Apartamento', TO_DATE('26111976','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('12', '17', '133', 'Casa', TO_DATE('22052012','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('13', '11', '188', 'Vila', TO_DATE('02102017','DDMMYYYY'),TO_DATE('22122022','DDMMYYYY'), 'I');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('14', '13', '15', 'Apartamento', TO_DATE('16032008','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('15', '23', '100', 'Condominio', TO_DATE('02062018','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('16', '32', '81', 'Apartamento', TO_DATE('12082011','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('17', '22', '7', 'Casa', TO_DATE('03022008','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('18', '16', '166', 'Vila', TO_DATE('04072007','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('19', '25', '194', 'Apartamento', TO_DATE('24122000','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('20', '13', '79', 'Condominio', TO_DATE('18101999','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('21', '4', '169', 'Apartamento', TO_DATE('05072018','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('22', '32', '38', 'Casa', TO_DATE('02012013','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('23', '19', '190', 'Vila', TO_DATE('22111999','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('24', '14', '117', 'Apartamento', TO_DATE('18102013','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('25', '11', '123', 'Condominio', TO_DATE('11062002','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('26', '6', '34', 'Apartamento', TO_DATE('24122012','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('27', '23', '70', 'Casa', TO_DATE('23052014','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('28', '13', '12', 'Vila', TO_DATE('20082010','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('29', '12', '25', 'Apartamento', TO_DATE('16031993','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('30', '14', '93', 'Condominio', TO_DATE('14081999','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('31', '11', '187', 'Apartamento', TO_DATE('26092012','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('32', '18', '56', 'Casa', TO_DATE('02042004','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('33', '39', '11', 'Vila', TO_DATE('16112020','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('34', '25', '30', 'Apartamento', TO_DATE('13092009','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('35', '24', '161', 'Condominio', TO_DATE('15032009','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('36', '8', '110', 'Apartamento', TO_DATE('07062014','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('37', '29', '23', 'Casa', TO_DATE('01081994','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('38', '22', '120', 'Vila', TO_DATE('01022002','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('39', '5', '197', 'Apartamento', TO_DATE('09102005','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('40', '25', '200', 'Condominio', TO_DATE('30072006','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('41', '37', '173', 'Apartamento', TO_DATE('24052017','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('42', '2', '174', 'Casa', TO_DATE('30032000','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('43', '25', '113', 'Vila', TO_DATE('14092021','DDMMYYYY'),NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('44', '15', '35', 'Apartamento', TO_DATE('07112013','DDMMYYYY'),NULL, 'A');

select * from mc_end_func;


-- Resposta do Comando SQL item e)

-- registro de cliente pessoa física I.

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'João da Silva', '4', 1185, 'A', 'joao.silva@gmail.com', '048 93222-1234', 'joao.silva@gmail.com', 'c7q3f6t8');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Maria Souza', '4', 2220, 'A', 'souza.maria@gmail.com.br', '047 3333-4567', 'souza.maria@gmail.com.br', 'senha245');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Pedro Santos', '4', 4984, 'A', 'pedrosantos@hotmail.com.br', '031 4444-7890', 'pedrosantos@hotmail.com.br', 'senha784');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Ana Oliveira', '1', 7534, 'A', 'santoseolive@outlook.com.br', '021 5555-4567', 'santoseolive@outlook.com.br', 'b5m2x8z9');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Gabriel Costa', '1', 5217, 'A', 'gcosta1248@hotmail.com', '011 93222-1234', 'gcosta1248@hotmail.com', 'z3v6n9p1');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Rafaela Nunes', '2', 9628, 'A', 'rafa.nun@yahoo.com', '031 3333-7890', 'rafa.nun@yahoo.com', 'senha123');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Lucas Carvalho', '4', 2356, 'A', 'lucarvalho@gmail.com', '034 98444-4567', 'lucarvalho@gmail.com', 'x7m5b2r9');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Juliana Mendes', '4', 9855, 'A', 'juli.1230@outlook.com', '034 8888-7777', 'juli.1230@outlook.com', 'd2t7f6q8');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Bruno Alves', '4', 896, 'A', 'brun.alves@yahoo.com', '021 99999-3333', 'brun.alves@yahoo.com', 'p9b2r8m5');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Larissa Oliveira', '5', 5985, 'A', 'larissa.oliveira19@gmail.com', '011 7777-4444', 'larissa.oliveira19@gmail.com', 'l8q4e2z1');


-- registro de cliente pessoa jurídica I.

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'ABC Indústria Ltda.', '5', 33517, 'A', 'ventas@abcindustria.com.br', '011 8888-7777', 'ventas@abcindustria.com.br', 'k9j1p6d4');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'XYZ Comércio Ltda.', '4', 59166, 'A', 'contato@xyzcomercio.com.br', '011 99999-3333', 'contato@xyzcomercio.com.br', 'senha1234');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Acme Consultoria', '2', 15134, 'A', 'contato@acme.com.br', '021 7777-4444', 'contato@acme.com.br', 'h3q1g7v9');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Delta Construtora', '1', 7800, 'A', 'contato@delta.com.br', '021 8888-5555', 'contato@delta.com.br', 't5r2e9w0');
INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Epsilon Tecnologia', '3', 60210, 'A', 'compras@epsilon.com.br', '031 2124-7894', 'compras@epsilon.com.br', '123senha');

SELECT * FROM MC_CLIENTE;

-- registro de cliente pessoa física II.

INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('1', TO_DATE('01011980','DDMMYYYY'), 'M', 'NULL', '123.456.789-00');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('2', TO_DATE('17021990','DDMMYYYY'), 'F', 'NULL', '234.567.890-12');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('3', TO_DATE('12081993','DDMMYYYY'), 'M', 'NULL', '345.678.901-23');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('4', TO_DATE('07041988','DDMMYYYY'), 'F', 'NULL', '456.789.012-34');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('5', TO_DATE('01011999','DDMMYYYY'), 'M', 'NULL', '567.890.123-45');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('6', TO_DATE('01021982','DDMMYYYY'), 'F', 'NULL', '678.901.234-56');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('7', TO_DATE('02032003','DDMMYYYY'), 'M', 'NULL', '789.012.345-67');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('8', TO_DATE('06051978','DDMMYYYY'), 'F', 'NULL', '890.123.456-78');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('9', TO_DATE('30091991','DDMMYYYY'), 'M', 'NULL', '901.234.567-89');
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) VALUES ('10', TO_DATE('07051987','DDMMYYYY'), 'F', 'NULL', '012.345.678-90');

SELECT * FROM MC_CLI_FISICA;

-- registro de cliente pessoa jurídica II.


INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) VALUES ('11', TO_DATE('01012000','DDMMYYYY'), '12.345.678/0001-00', '567890123004');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) VALUES ('12', TO_DATE('28122005','DDMMYYYY'), '23.456.789/0001-01', '678901234005');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) VALUES ('13', TO_DATE('06051988','DDMMYYYY'), '34.567.890/0001-02', '789012345006');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) VALUES ('14', TO_DATE('07042015','DDMMYYYY'), '45.678.901/0001-03', '890123456007');
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) VALUES ('15', TO_DATE('30032022','DDMMYYYY'), '56.789.012/0001-04', '901234567008');

SELECT * FROM MC_CLI_JURIDICA;

-- registro de endereço de clientes

-- atualizando a coluna cd_logradouro_cli a cd_logradouro no banco de dados.

ALTER TABLE mc_end_cli RENAME COLUMN cd_logradouro_cli TO cd_logradouro;

ALTER TABLE mc_end_cli DROP CONSTRAINT fk_mc_logradouro_end;
ALTER TABLE mc_end_cli ADD CONSTRAINT fk_mc_logradouro_end FOREIGN KEY ( cd_logradouro )
        REFERENCES mc_logradouro ( cd_logradouro );

COMMENT ON COLUMN mc_end_cli.cd_logradouro IS
    'Esta coluna irá receber o código do logradouro  do cliente e seu conteúdo é obrigatório.';

-- execução de scrip para popular tabela com endereço.

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('1', '25', '81', 'Apartamento', TO_DATE('21012001','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('2', '32', '190', 'Casa', TO_DATE('14122021','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('3', '9', '87', 'Vila', TO_DATE('24052011','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('4', '17', '99', 'Apartamento', TO_DATE('07041988','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('5', '33', '145', 'Condominio', TO_DATE('01011999','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('6', '10', '171', 'Apartamento', TO_DATE('01021982','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('7', '14', '166', 'Apartamento', TO_DATE('03122005','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('8', '16', '150', 'Casa', TO_DATE('12122018','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('9', '18', '40', 'Vila', TO_DATE('10082006','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('10', '40', '117', 'Apartamento', TO_DATE('17042010','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('11', '35', '15', 'Edíficio', TO_DATE('07082011','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('12', '37', '35', 'Edíficio', TO_DATE('11062007','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('13', '19', '8', 'Andar', TO_DATE('06051988','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('14', '20', '200', 'Apartamento', TO_DATE('07042015','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES ('15', '15', '850', 'Edíficio', TO_DATE('26022023','DDMMYYYY'), NULL, 'A');

SELECT * FROM MC_END_CLI;

-- Resposta do Comando SQL item K)
-- Não é possível registrar um novo cliente com um nome de login já registrado porque existe uma constraint unique aplicada ao campo nm_login.

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL, 'Jose Gazcon', '4', 1185, 'A', 'joao.silva@gmail.com', '048 99213-4212', 'joao.silva@gmail.com', 'cdef1230');

-- Resultado: ORA-00001: unique constraint (SQL_QNTVABNUCLAMXMYTJNYSLGBAG.UK_MC_CLIENTE_MM_LOGIN) violated ORA-06512: at "SYS.DBMS_SQL", line 1721


-- Resposta do Comando SQL item g)

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Artesanato', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Áudio', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Brinquedos', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Celular e Smartphone', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Colchões', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Esporte e Lazer', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Ferramentas', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Games', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Informática', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Livros', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Pet Shop', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'TV e Utilidades Domésticas', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');

SELECT * FROM MC_CATEGORIA_PROD;

-- Resposta do Comando SQL item h)

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Instalação do produto', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Uso no cotidiano', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Comercial com personalidade', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Viagem e Turismo', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Moda e Acessórios', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Decoração e Design', TO_DATE('01012022','DDMMYYYY'), NULL, 'A');

-- Resposta do Comando SQL item i)

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '14', '7894561230011', 'Jogo de tapetes de crochê', 163.99, 'Envelope plast', 'A', '30', 'Conjunto de tapetes artesanais feitos em crochê, ideais para decorar e proteger o piso de ambientes internos.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '3', '7891234560087', 'Casa Barbie Dreamhouse', 120.99, 'Cx de papelão', 'A', '36', 'Casa de bonecas da famosa boneca Barbie, com diversos cômodos e acessórios para as crianças se divertirem.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '2', '9876543210054', 'Fones de ouvido sem fio', 5328.99, 'Envelope plast', 'A', '16', 'Fones de ouvido com tecnologia bluetooth, sem fio, com ótima qualidade de som e conforto para o uso diário.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '4', '6547891230020', 'iPhone 13', 2702.99, 'Cx de papelão', 'A', '23', 'Smartphone da marca Apple, com tela de alta definição, câmera de última geração e recursos avançados de segurança e privacidade.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '4', '3214567890096', 'Smartphone Samsung Galaxy S20 Fe', 4797.99, 'Cx de papelão', 'A', '42', 'Celular de última geração da Samsung, com tela de alta definição, bateria duradoura e câmera com múltiplas lentes.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '5', '4563217890060', 'Colchão de molas ensacadas Pro Max', 6640.99, 'Sacola plast', 'A', '21', 'Colchão de molas ensacadas com alta tecnologia de conforto e suporte, ideal para noites de sono mais tranquilas e reparadoras.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '6', '7899876540031', 'Bicicleta ergométrica', 5509.99, 'Cx de papelão', 'A', '25', 'Equipamento de ginástica com pedalada fixa, que ajuda a manter a forma física e a saúde em dia.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '7', '1237894560004', 'Conjunto de chaves de fenda e chaves Phillips', 477.99, 'Envelope plast', 'A', '27', 'Kit de ferramentas com diversas chaves de fenda e phillips, para uso doméstico ou profissional.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '8', '3217894560072', 'Playstation 5', 5853.99, 'Cx de papelão', 'A', '44', 'Console de jogos de última geração, com alta definição e recursos avançados de jogabilidade.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '9', '4569873210046', 'Notebook Lenovo ThinkPad', 6352.99, 'Cx de papelão', 'A', '29', 'Computador portátil de alta performance, ideal para trabalhar ou estudar em qualquer lugar.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '9', '6541237890014', 'Monitor Gamer Samsung 27" Ips Wide 75 Hz Full Hd', 3441.99, 'Cx de papelão', 'A', '30', 'Monitor de alta definição com tela ampla, ideal para jogos e uso profissional.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '10', '7896541230081', 'A Metamorfose, de Franz Kafka', 194.99, 'Envelope plast', 'A', '30', 'Livro clássico da literatura mundial, com uma história fascinante e envolvente sobre a transformação de um homem em inseto.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '10', '1234567890057', 'Box Harry Potter Premium Verde - 7 Livros, de J.K. Rowling', 52.99, 'Envelope plast', 'A', '30', 'Box com os sete livros da série Harry Potter, uma das mais famosas da literatura infanto-juvenil de todos os tempos.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '11', '7897894560028', 'Ração para gatos 20kg', 120.99, 'Sacola plast', 'A', '40', 'Alimento completo e balanceado para gatos, com todos os nutrientes necessários para uma alimentação saudável.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '11', '4561237890092', 'Ração para cachorros 20kg', 120.99, 'Sacola plast', 'A', '37', 'Alimento completo e balanceado para cães, com todos os nutrientes necessários para uma alimentação saudável.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '12', '3217896540066', 'Smart TV LED 4K', 6957.99, 'Cx de papelão', 'A', '38', 'Televisor de alta definição com tecnologia 4K, ideal para filmes, séries e jogos com qualidade de imagem excepcional.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '12', '9874561230035', 'Ar condicionado split', 5552.99, 'Cx de papelão', 'A', '18', 'Equipamento de climatização para ambientes, com controle de temperatura e umidade, ideal para dias de calor intenso.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '14', '7893214560009', 'Conjunto de panelas', 6525.99, 'Cx de papelão', 'A', '45', 'Kit de panelas com diversas opções de tamanhos e materiais, ideais para');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '15', '7896547890077', 'Kit de churrasco personalizado', 4465.99, 'Cx de papelão', 'A', '37', 'Kit de churrasco com itens personalizados, incluindo tábua de corte, faca, garfo, avental e outros acessórios.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '17', '7891237890041', 'Mala De Bordo Para Viagem', 2861.99, 'Cx de papelão', 'A', '38', 'Mala de bordo resistente com rodinhas, alça retrátil e várias divisórias para organizar as roupas e objetos.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '17', '7891237890041', 'Óculos de sol Ray-Ban', 4109.99, 'Cx de papelão', 'A', '32', 'Óculos de sol de marca Ray-Ban com armação e lentes de alta qualidade, design moderno e proteção UV.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '18', '7891237890041', 'Tapete persa', 5765.99, 'Cx de papelão', 'A', '29', 'Tapete artesanal com padrões tradicionais persas, feito de materiais de alta qualidade e durabilidade.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '3', '7891237890041', 'Jogo de Xadrez de mármore', 4585.99, 'Cx de papelão', 'A', '44', 'Jogo de xadrez elegante com peças feitas de mármore, incluindo tabuleiro e caixa para armazenamento.');
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '3', '7891237890041', 'Quebra-Cabeça Mapa Do Brasil', 188.99, 'Cx de papelão', 'A', '32', 'Quebra-cabeça educativo com mapa do Brasil em várias peças, adequado para todas as idades.');

SELECT * FROM MC_PRODUTO;

-- Resposta do Comando SQL item j)

INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD) VALUES ('2', SQ_MC_SGV_VISUAL_PROD.NEXTVAL, '14', NULL, NULL, NULL, 'A');
INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD) VALUES ('2', SQ_MC_SGV_VISUAL_PROD.NEXTVAL, '15', NULL, NULL, NULL, 'A');

SELECT * FROM MC_SGV_PRODUTO_VIDEO;


-- Resposta do Comando SQL item K)
-- criação do script de sequência para cd_visualizacao_video

CREATE SEQUENCE SQ_MC_SGV_VISUALIZACAO_VIDEO
INCREMENT BY 1 
MAXVALUE 9999999999 
NOCACHE 
NOCYCLE;

-- carga das visualizações:

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO) VALUES (SQ_MC_SGV_VISUALIZACAO_VIDEO.NEXTVAL, '2', '2', TO_DATE('11052022 162234','DDMMYYYY HH24MISS'), EXTRACT(HOUR FROM TO_TIMESTAMP('11052022 162234', 'DDMMYYYY HH24MISS')),EXTRACT(MINUTE FROM TO_TIMESTAMP('11052022 162234', 'DDMMYYYY HH24MISS')),EXTRACT(SECOND FROM TO_TIMESTAMP('11052022 162234', 'DDMMYYYY HH24MISS')));
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO) VALUES (SQ_MC_SGV_VISUALIZACAO_VIDEO.NEXTVAL, '3', '3', TO_DATE('25032023 091827','DDMMYYYY HH24MISS'), EXTRACT(HOUR FROM TO_TIMESTAMP('25032023 091827', 'DDMMYYYY HH24MISS')),EXTRACT(MINUTE FROM TO_TIMESTAMP('25032023 091827', 'DDMMYYYY HH24MISS')),EXTRACT(SECOND FROM TO_TIMESTAMP('25032023 091827', 'DDMMYYYY HH24MISS')));
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO) VALUES (SQ_MC_SGV_VISUALIZACAO_VIDEO.NEXTVAL, '4', '4', TO_DATE('08062022 205412','DDMMYYYY HH24MISS'), EXTRACT(HOUR FROM TO_TIMESTAMP('08062022 205412', 'DDMMYYYY HH24MISS')),EXTRACT(MINUTE FROM TO_TIMESTAMP('08062022 205412', 'DDMMYYYY HH24MISS')),EXTRACT(SECOND FROM TO_TIMESTAMP('08062022 205412', 'DDMMYYYY HH24MISS')));
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO) VALUES (SQ_MC_SGV_VISUALIZACAO_VIDEO.NEXTVAL, '5', '5', TO_DATE('03122022 143056','DDMMYYYY HH24MISS'), EXTRACT(HOUR FROM TO_TIMESTAMP('03122022 143056', 'DDMMYYYY HH24MISS')),EXTRACT(MINUTE FROM TO_TIMESTAMP('03122022 143056', 'DDMMYYYY HH24MISS')),EXTRACT(SECOND FROM TO_TIMESTAMP('03122022 143056', 'DDMMYYYY HH24MISS')));
INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO) VALUES (SQ_MC_SGV_VISUALIZACAO_VIDEO.NEXTVAL, '6', '6', TO_DATE('30072022 075912','DDMMYYYY HH24MISS'), EXTRACT(HOUR FROM TO_TIMESTAMP('30072022 075912', 'DDMMYYYY HH24MISS')),EXTRACT(MINUTE FROM TO_TIMESTAMP('30072022 075912', 'DDMMYYYY HH24MISS')),EXTRACT(SECOND FROM TO_TIMESTAMP('30072022 075912', 'DDMMYYYY HH24MISS')));

SELECT * FROM MC_SGV_VISUALIZACAO_VIDEO;


-- Resposta do Comando SQL item l) 

-- Confirma as transações pendentes
COMMIT;


-- Resposta do Comando SQL item m)

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Móveis', TO_DATE('01012022','DDMMYYYY'), NULL, 'I');

SELECT * FROM MC_CATEGORIA_PROD;


-- Resposta do Comando SQL item n) 

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD) VALUES (SQ_MC_PRODUTO.NEXTVAL, '3', '7891237890025', 'Lego Classic - Caixa Grande De Peças Criativas - 790 Peças', 382.99, 'Cx de papelão', 'I', '32', 'Construa muitas coisas com esta caixa grande de peças clássicas LEGO em 33 cores diferentes. Com muitas janelas e portas diferentes, juntamente com outras peças especiais que o vão inspirar a imaginação.');

SELECT * FROM MC_PRODUTO;


-- Resposta do Comando SQL item o)

SELECT * FROM MC_FUNCIONARIO;
SELECT * FROM MC_FUNCIONARIO WHERE cd_funcionario = 44;

UPDATE MC_FUNCIONARIO
SET VL_SALARIO = VL_SALARIO * 1.12
WHERE cd_funcionario = 44;


-- Resposta do Comando SQL item p)

SELECT * FROM MC_CATEGORIA_PROD;
SELECT * FROM MC_CATEGORIA_PROD WHERE CD_CATEGORIA = 10;

UPDATE MC_CATEGORIA_PROD
SET DS_CATEGORIA = 'Livros e papelaria'
WHERE CD_CATEGORIA = 10;


-- Resposta do Comando SQL item q)

SELECT * FROM MC_DEPTO;
SELECT * FROM MC_DEPTO WHERE CD_DEPTO = 4;

UPDATE MC_DEPTO
SET NM_DEPTO = 'CONTÁBIL E FISCAL'
WHERE NM_DEPTO = 'CONTABILIDADE';


-- Resposta do Comando SQL item r)

SELECT * FROM MC_CLI_FISICA WHERE NR_CLIENTE = 1;

UPDATE MC_CLI_FISICA
SET DT_NASCIMENTO = TO_DATE(18052002,'DDMMYYYY')
WHERE NR_CLIENTE = '1';


-- Resposta do Comando SQL item s)

SELECT * FROM MC_CATEGORIA_PROD;

UPDATE MC_CATEGORIA_PROD
SET DS_CATEGORIA = 'Viagem e Turismo Nacional'
WHERE CD_CATEGORIA = 16;
SELECT * FROM MC_CATEGORIA_PROD WHERE CD_CATEGORIA = 16;


-- Resposta do Comando SQL item t)

SELECT * FROM MC_FUNCIONARIO;
SELECT * FROM MC_FUNCIONARIO WHERE CD_FUNCIONARIO = 23;

UPDATE mc_funcionario
SET ST_FUNC = 'I',
DT_DESLIGAMENTO = SYSDATE
WHERE CD_FUNCIONARIO = 23


-- Resposta do Comando SQL item u)


INSERT INTO MC_SGV_SAC (
NR_SAC,
NR_CLIENTE,
CD_PRODUTO,
CD_FUNCIONARIO,
DS_DETALHADA_SAC,
DT_ABERTURA_SAC, 
HR_ABERTURA_SAC,
DT_ATENDIMENTO,
HR_ATENDIMENTO_SAC,
NR_TEMPO_TOTAL_SAC,
DS_DETALHADA_RETORNO_SAC,
TP_SAC,
ST_SAC,
NR_INDICE_SATISFACAO
) VALUES (
SQ_MC_SGV_SAC.NEXTVAL,
'1',
'3',
'22',
'Preciso que reenviem a nfe e o contato da assistênica técnica',
TO_DATE('13052022 131124','DDMMYYYY HH24MISS'),
EXTRACT(HOUR FROM TO_TIMESTAMP('13052022 131124','DDMMYYYY HH24MISS')),
TO_DATE('14052022 102545','DDMMYYYY HH24MISS'),
EXTRACT(HOUR FROM TO_TIMESTAMP('14052022 102545','DDMMYYYY HH24MISS')),
NULL,
'Reenvio de nfe, verificando contato da assistencia técnica e suporte da marca',
'D',
'E',
NULL);

select * from MC_SGV_SAC;

-- atualização do atendimento e fechamento.


UPDATE MC_SGV_SAC
SET DS_DETALHADA_RETORNO_SAC = 'Contato da assistência técnica e suporte enviados',
ST_SAC = 'F',
DT_ATENDIMENTO = TO_DATE('14052022 182530','DDMMYYYY HH24MISS'),
HR_ATENDIMENTO_SAC = EXTRACT(HOUR FROM TO_TIMESTAMP('14052022 182530','DDMMYYYY HH24MISS')),
NR_TEMPO_TOTAL_SAC = EXTRACT(HOUR FROM NUMTODSINTERVAL(DT_ATENDIMENTO - DT_ABERTURA_SAC, 'DAY')),
NR_INDICE_SATISFACAO = 9
WHERE NR_SAC = 1;

SELECT * FROM MC_SGV_SAC WHERE NR_SAC = 1;


-- Resposta do Comando SQL item v)

UPDATE MC_END_CLI
SET ST_END = 'I',
DT_TERMINO = TO_DATE(TO_CHAR(TRUNC(SYSDATE) - 1, 'DDMMYYYY'), 'DDMMYYYY')
WHERE NR_CLIENTE = 3;
SELECT * FROM MC_END_CLI WHERE NR_CLIENTE = 3


-- Resposta do Comando SQL item w)

UPDATE MC_END_FUNC
SET ST_END = 'I',
DT_TERMINO = TO_DATE(TO_CHAR(TRUNC(SYSDATE) - 1, 'DDMMYYYY'), 'DDMMYYYY')
WHERE CD_FUNCIONARIO = 20;
SELECT * FROM MC_END_FUNC WHERE CD_FUNCIONARIO = 20


-- Resposta do Comando SQL item x)

-- Não é possível eliminar o estado porque é usado como chave estrangeira - FK -  na tabela de cidade. Para eliminar o estado sería necessário eliminar também o constraint da FK.

SELECT * FROM MC_ESTADO;

DELETE FROM MC_ESTADO
WHERE SG_ESTADO = 'BA';

-- error após execução do script:
-- ORA-02292: integrity constraint (SQL_UNUTPXBAUQRFDFDKYSRBOSEDE.FK_MC_CIDADE_ESTADO) violated - child record found ORA-06512: at "SYS.DBMS_SQL", line 1721


-- Resposta do Comando SQL item y)

-- Não é possível atualizar o status do produto a 'X' porque o constraint Check só permite os valores 'A' ou 'I', para continuar sería necessário alterar ou eliminar a constraint.

UPDATE MC_PRODUTO
SET ST_PRODUTO = 'X',
WHERE CD_PRODUTO = 10
SELECT * FROM MC_PRODUTO WHERE CD_PRODUTO = 10
-- erro: ORA-02290: check constraint (SQL_UNUTPXBAUQRFDFDKYSRBOSEDE.CK_MC_PRODUTO_ST_PRODUTO) violated ORA-06512: at "SYS.DBMS_SQL", line 1721


-- Resposta do Comando SQL item z) 

-- Confirma as transações pendentes
COMMIT;