CREATE OR REPLACE PROCEDURE fun_mc_gera_aliquota_media_icms_estado(p_sg_estado IN VARCHAR2, p_aliquota OUT NUMBER) IS BEGIN IF p_sg_estado = 'AC' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'AL' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'AM' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'AP' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'BA' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'CE' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'DF' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'ES' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'GO' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'MA' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'MG' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'MS' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'MT' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'PA' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'PB' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'PE' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'PI' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'PR' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'RJ' THEN p_aliquota := 20.0;
ELSIF p_sg_estado = 'RN' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'RO' THEN p_aliquota := 17.5;
ELSIF p_sg_estado = 'RR' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'RS' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'SC' THEN p_aliquota := 17.0;
ELSIF p_sg_estado = 'SE' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'SP' THEN p_aliquota := 18.0;
ELSIF p_sg_estado = 'TO' THEN p_aliquota := 18.0;
ELSE p_aliquota := 4.0;
END IF;
END;